argocd-config:
  project: default
  description: AppProject that hosts your application
  # docstring as an example
  appofapps:
    test:
      path: apps/app-of-apps
      apps:
        crossplane:
          targetRevision: HEAD
          path: apps/crossplane
          repo: test
          syncPolicy: {
            syncOptions: {}
          }
