argocd-config:
  project: default
  description: AppProject that hosts your application
  # docstring as an example
  appofapps:
    dev:
      apps:
        crossplane:
          path: apps/app-of-apps/crossplane
        kyverno:
          path: apps/app-of-apps/kyverno
    test:
      path: apps/app-of-apps
      valuesFile: values-tst.yaml
