argocd-config:
  project: default
  description: AppProject that hosts your application
  # docstring as an example
  appofapps:
    dev:
      path: apps/app-of-apps
      valuesFile: values-dev.yaml
    test:
      path: apps/app-of-apps
      valuesFile: values-tst.yaml
