argocd-config:
  project: default
  description: AppProject that hosts your application
  # docstring as an example
  appofapps:
    test:
      apps:
        test-app:
          targetRevision: main
          path: ./test-app
          repo: test
          syncPolicy: {
            syncOptions: {}
          }
