apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: {{ $.Release.Namespace }}
spec:
  project: default
  source:
    repoURL: 'https://charts.crossplane.io/stable'
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "crossplane"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

