apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $.Values.project }}
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  description: ''
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace

