base_path: apps
destination:
  server: https://kubernetes.default.svc
argocd-config:
  apps:
    crossplane:
      targetRevision: HEAD
      path: apps/crossplane
      repo: test
      syncPolicy: {
        syncOptions: {}
      }

